### ISSUE TITLE
Vulnerability in PredictableCryptographicKeyABHCase1.java

### ISSUE THREAD

**Issue by ericbodden** [CryptoGuardOSS/cryptoapi-bench#2]
According to your table, PredictableCryptographicKeyABHCase1.java should not contain any vulnerability, but it does. The code stores secret key material in a string. This is no good. The VM can cache strings forever, and good crypto-misuse checkers should warn about this kind of vulnerability.

**Comment by sazzad114** [comment]
This is true. The current benchmark doesn't cover this vulnerability. Soon, we will update our benchmark to include this warning. Thanks!

**Comment by ShaAfr** [comment]
Thank you for pointing the issue. It has been fixed in the updated benchmark. 
https://github.com/CryptoAPI-Bench/CryptoAPI-Bench
